//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dinner
    {
        public int id { get; set; }
        public string bezeichnung { get; set; }
        public decimal preis { get; set; }
        public string gang1 { get; set; }
        public string gang2 { get; set; }
        public string gang3 { get; set; }
        public string gang4 { get; set; }
        public string gang5 { get; set; }
    }
}
