//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extras
    {
        public int id { get; set; }
        public Nullable<bool> Babybett { get; set; }
        public Nullable<bool> Kinderstuhl { get; set; }
        public Nullable<bool> Kinderbetreuung { get; set; }
        public Nullable<bool> KinderProgramm { get; set; }
    }
}
