//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rueckruf
    {
        public int id { get; set; }
        public string name { get; set; }
        public string telefon { get; set; }
        public string grund { get; set; }
        public System.DateTime datum_erhalten { get; set; }
        public Nullable<System.DateTime> datum_erledigt { get; set; }
    }
}
